### ISSUE TITLE
备稿：4月9日 日常分享（张柯）

### ISSUE THREAD

**Issue by gsk475** [zsqk/news#19]

**Comment by koulerz** [comment]
# 前言
通过了解哲学家们思考的问题能够帮助我们更加简单和通俗的认识到哲学是一门什么样的学科以及哲学家都在做些什么事情。从而对哲学产生一个相对准确和客观印象。

# 前苏格拉底时代（公元前700~公元前370）
**前苏格拉底时代对应中国的春秋战国时期，老子，孔子的时代**

1. `泰勒斯`通过观察水的形态变化提出`水是构成世界的基本材料`
2. `毕达哥拉斯`通过思考数学公式的确定性提出`数字是宇宙的统治者`
3. `普罗塔哥拉`提出`人是万物的尺度`，因为一个人看起来是正确的事情，另一个人可能会认为是错误的。
4. `德谟克利特`提出原子论`世间是由原子和虚空组成的`

**前苏格拉底时代的哲学问题大部门集中在对自然哲学的思考，比如客观世界的原貌，万物的构成。**

# 经典希腊时代（公元前470~公元前250）
**经典希腊时代对应中国的战国时期**

1. `苏格拉底`思考的问题是`什么才是好的生活，生命的意义是什么。提出善是事物的本性，是万物追求的目标`
2. `柏拉图`思考的问题是`人类如何分辨出万物的正确的，完美的最本质的基本形态`。比如我们看到不同品种不同形态不同颜色的猫都能分辨出来，那么必然所有的猫都有某种共同特征。这种由共同特征所组成的完美形态的猫才是我们应该去认识的。而现实世界只不过是这种完美形态的复制模型。    
为此`柏拉图`提出一个“洞穴比喻”来说明。他让人们想象出一个洞穴，囚犯面向墙壁被绑在洞穴中，身后是一个火堆。囚犯和火堆之间不时有人走动或拿起不同物体，这些物体的影子反映在洞穴墙壁上。那么这些囚犯实际上并不能真正了解事物本身。柏拉图觉得`人类感官所感知到的物质世界正如洞穴墙壁上的影子一样，是现实的缩影`。    
这种对人类认识的质疑和问题通常被归为`形而上学`。`形而上学`是哲学的一个门类，研究世界的本质。比如超自然世界的本原，灵魂是否存在，自由意志是否存在等。通常对于`形而上学`的理解误区在于这一概念本身的形式，它不常与其他学科放在一起，我们会认为形而上学是一个概念而非学科。实际上它和数学，化学，物理学这些文字形式类似，当我们说某一问题是物理问题时，意味着这一问题属于物理学范畴。而当我们说某一问题是形而上的，也就意味着这一问题属于形而上学这门学科。
3. `亚里士多德`与柏拉图相反，柏拉图质疑自己的感官，而`亚里士多德`认为`我们是通过感知来认识世界的`。他认为现实世界中的物体并非物体完美形态的复制模型。我们应当通过研究个体来认识某一种类共有的本质。比如研究不同的猫得出猫共有的本质属性。对于公正，美德这些概念，我们只能通过观察他们在现实世界的各种不同呈现方式来逐渐修正对他们的了解和认识。    
`亚里士多德`按照生物的特征对生物进行了归类。在这过程中制定了一套成系统的逻辑形式。期望运用逻辑推理出事实。例如，我们通过两个命题“所有人都会死”和“苏格拉底是人”可以推理出“苏格拉底会死”的结论。
4. `伊壁鸠鲁`认为`人应当在短暂的人生中享乐。这种快乐并不是纯粹的身体感受到的世俗快乐，而是身体的没有痛苦和灵魂的不受干扰，是一种平静状态。`。
5. `芝诺`认为`宇宙有自己的规律，自然法则是宇宙的主宰。人应该遵循自然法则，追求各自与自然达成的和谐状态`。

**从苏格拉底开始，哲学家们开始关注对人本身的思考和探究。**

**受限于当时的知识水平，其中某些理论可能被现代人认为是简单的，不值一提的，甚至是错误的，但我们也不能否认他们在自己所处的年代开创出这些理论的革命性，和对人类文明后续发展的重要性。现代的很多领域中我们仍然能够清晰的看到这些理论所留下的印记。**

# 参考
- [哲学百科](https://book.douban.com/subject/25810167/)
- [西方哲学史思维导图 1](https://yangjh.gitee.io/philosophymindmap/)
- [西方哲学史思维导图 2](https://mm.edrawsoft.cn/template/1478)
- [西方哲学史思维导图 3](https://wemp.app/posts/cc88c2c3-1491-4486-9b43-fb6be5778cbc)
