### ISSUE TITLE
备稿计划: 使用 Aliyun OSS + CDN 部署 React 单页应用

### ISSUE THREAD

**Issue by iugo** [zsqk/news#32]
1. 使用 react-scripts 创建 React 单页应用.
2. 使用 react-router-dom 5 作为路由.
3. 使用 Aliyun OSS.
4. 使用 Aliyun (D)CDN.
5. 配置 OSS 镜像回源, 或在 CDN 中配置 Rewrite 重写.
6. 使用 ossutil 自动发版.

网上查不到太多有效信息, 自己翻找 Aliyun 后台设置. 可能比较简单, 或者没什么人用吧.

**Comment by Adherentman** [comment]
请教一下，这个第五项该如何配置。
<img width="1440" alt="iShot2021-05-12 21 54 55" src="https://user-images.githubusercontent.com/26477346/117989806-2e08c300-b36f-11eb-832f-2db1277c5ba1.png">
我是browerHistory这样设置了在页面刷新也没有用。。

**Comment by iugo** [comment]
> 请教一下，这个第五项该如何配置。
> <img alt="iShot2021-05-12 21 54 55" width="1440" src="https://user-images.githubusercontent.com/26477346/117989806-2e08c300-b36f-11eb-832f-2db1277c5ba1.png">
> 我是browerHistory这样设置了在页面刷新也没有用。。

我更建议配置 CDN.

如果要配置 OSS, 大概是跳转固定地址, 而不是添加前后缀. 然后需要携带请求字符串.

如果用阿里的 CDN, 名字叫作全站加速 CDN.

**Comment by Adherentman** [comment]
设置跳转固定地址也不奏效。。设置cdn也无效。。
![image](https://user-images.githubusercontent.com/26477346/118105759-61029380-b40f-11eb-93a8-4c70a4a8d4d5.png)
我甚至待重写URI 改为 /users
目标： /index.html
然后去http://xxx.com/users 之后刷新还是依然没找到

**Comment by Adherentman** [comment]
突然奇想。。在OSS的404页面也返回index.html 这样也不用cdn之类的。。您对这种方法有任何看法吗

**Comment by iugo** [comment]
@Adherentman 对于单页应用, 都是应该重定向到 index.html 的, 但是 JS 可以将浏览器的 URL 修改一下.

比如访问 `https://abc.dd/page1`, HTTP 返回值要是 index.html 的内容. index.html 引导 JS 加载后, JS 可以看到当前的 URL 为 `https://abc.dd/page1`, 然后 JS 就进行路由, 选择渲染匹配 page1 的内容.

**Comment by iugo** [comment]
> 突然奇想。。在OSS的404页面也返回index.html 这样也不用cdn之类的。。您对这种方法有任何看法吗

可以不用 CDN, 但 CDN 适当优化后更便宜.

我看到你在阿里云上选择的不是 Break, 选 Break 就可以了, 不要做 301 或者 302, 不适合单页应用.

**Comment by Adherentman** [comment]
> @Adherentman 对于单页应用, 都是应该重定向到 index.html 的, 但是 JS 可以将浏览器的 URL 修改一下.
> 
> 比如访问 `https://abc.dd/page1`, HTTP 返回值要是 index.html 的内容. index.html 引导 JS 加载后, JS 可以看到当前的 URL 为 `https://abc.dd/page1`, 然后 JS 就进行路由, 选择渲染匹配 page1 的内容.

就上面情况而言，我从https://xxx.com/page1 中的按钮点击跳转到 https://xxx.com/page2。
之后我在https://xxx.com/page2 刷新页面，url变成了https://xxx.com/index.html
这种情况JS并没有自动去路由，我尝试去改了很多变量也没有效果。。

**Comment by ggbond2077** [comment]
https://help.aliyun.com/document_detail/396285.html
阿里云官网文档写的就是 404 到 index.html

**Comment by iugo** [comment]
> https://help.aliyun.com/document_detail/396285.html 阿里云官网文档写的就是 404 到 index.html

原 issue 正文写于两年前, 那时 OSS 至少还没有错误响应码可以改为 200 这一有用的功能.

随着阿里云的发展, 以前 trick 的办法现在都有更加正式的, 更好的方案.
