### ISSUE TITLE
4月22日 日常分享

### ISSUE THREAD

**Issue by gsk475** [zsqk/news#38]

**Comment by vvvvvvvvvvip** [comment]
前一段时间亦凡找我扒网站 然后思珂同学推荐了这个**仿站小工具8.1**

**介绍**
仿站小工具8.1是一款用来下载网页模板的软件，可以将指定目标网站的资源内容快速索引读取并复制到本地使用的软件工具！可以通过该软件检测网编码，下载网页，它会从html的代码中将JS、Css、Image、Picture、Flash等静态文件网址提取过来，再从下载完好的Css代码中提取出Image静态文件网址，通过网址下载静态文件，根据软件设置好的保存规则，自动修正html和css代码链接路径，最终这些静态文件被按分类保存到电脑文件夹。并且会自动分类归档。
**软件特色**
    1. 从输入的网址下载html代码。
    2. 支持提取JS、Css、Image、Picture、Flash等静态文件网址。
    3. 可根据软件设置好的保存规则，自动修正html和css代码链接路径。
**使用教程**
1. [输入需要下载的网页的网址，点击添加。](url
![image](https://user-images.githubusercontent.com/19698815/79931742-47964e80-847e-11ea-88d3-8f520284dbe8.png)
)
2. [选择保存地址，点击开始下载。](url
![image](http://www.xue51.com/uppic/180404/201804041643079989.png)
)
3. [等待下载完成，打开保存地址里面的文件就可以了。](url
![image](http://www.xue51.com/uppic/180404/201804041643144531.png)
)
