### ISSUE TITLE
备稿：一行代码让世界充满爱

### ISSUE THREAD

**Issue by gsk475** [zsqk/news#45]
## 一行暖心的代码，让世界充满爱~

有时用户在访问页面找不到网站的资源时，就会提示404错误。作为网站的开发者，最好应该自己定制404页面，引导用户返回到网站，防止用户流失。

#### 你知道吗？
在自己定制404页面时，只需要在网站中加入一行代码，就能为公益尽一份力。这个页面叫做`公益404页面`

#### 介绍
公益404页面是由腾讯公司员工志愿者自主发起的互联网公益活动。

网站只需要在自己的404页面中嵌入一段简单的代码，就能通过互联网来迅速传播失踪儿童信息，从而提高找回失踪儿童的概率。失踪儿童信息来自宝贝回家寻子网。

#### 代码
复制以下 js 代码，嵌入到您的 404 页面，可以自适应移动设备

##### 注意事项  
如果一个 404 页面的内容小于 512B，IE 会认为该 404 页面不够友好，在 IE 下将不会成功返回该 404 错误页面

```
<script type="text/javascript" src="//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js" charset="utf-8"></script>
```

同时`homePageUrl`、`homePageName`两个参数,提高页面定制性

```
<script type="text/javascript" src="//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js" charset="utf-8" homePageUrl="返回页面路径" homePageName="返回页面名称"></script>
```

**文章内容参考：**：https://www.qq.com/404/

**Comment by iugo** [comment]
1. 如果不是原创, 注明出处.
2. 通过 404 这种问题页面, 能达到的功效有限, 如果网站做的好, 正常情况没有 404, 那就没作用.
3. 腾讯这个项目应该没人维护了, 数据都是 2017 年的. 如果不是社区项目, 那么公司就有责任做好, 数据来源, 必要的公示, 反馈途径等.
