### ISSUE TITLE
备稿：5月21日 分享

### ISSUE THREAD

**Issue by gsk475** [zsqk/news#57]

**Comment by koulerz** [comment]
# 《未来 50 年》读书总结

## 前言
《未来 50 年》是一部文集，许多前沿领域的科学家们展望未来 50 年的科学成就和可能有所突破的技术领域。本书正是他们的思考汇聚而成。

本书英文第一版出版于 21 世纪初， 2002 年，距今已经过去 18 年。透过书中的内容我们可以简略的了解到最前沿的科学和其发展方向。学者们对于未来的预测也得以让我们一窥科学发展的趋势。例如，我们对于未来的把握是否过于乐观或悲观。有多少知识是按照我们预想的节奏被发现和总结，又有多少爆炸性的新发现的对我们现有知识系统产生了巨大且深远的影响。

本书的作者大多是最前沿科学研究的学者和专家，涉及到的话题也必然有所局限。在我们大胆的展望未来时，也不应忽略其他基础学科的贡献。

下面是以学科领域的维度列出了本书中作者们提出的问题和见解。

## 宇宙和太空探索
- 宇宙大爆炸更详细的解释
- 占宇宙密度80%到95%的暗物质和暗能量由什么组成
- 星系如何形成
- 地球生命是如何开始的
- 我们有望在月球，火星和环绕木星的轨道上建立基地，源源不断的激发我们的想象力和好奇心。帮助我们探索宇宙的奥秘。

## 物理学
- 量子物理的合理解释
- 引力的量子理论是什么
- 基本粒子的性质和解释
- 建立物理学的统一理论

## 化学
- 我们将深入认识更小微粒之间的化学反应和相互作用。

## 医学
- 越来越多人会变得抑郁。
    - 生活会越来越紧张
    - 通过药物治疗并不是很有效

## 生物学
- 生命的定义。我们可能会发现更多能够协同演化的生命系统。更精确的定义生命的本质含义。
- 对基因的认识和改变。现在实验室能够诱发从小鸡嘴里生出嫩芽，诱发蛇长出腿。到 2050 年，我们有望重构一般恐龙的基因组。
- 我们将通过机器改善自身。恢复残障人的能力甚至赋予人类更强大的超能力。

## 神经科学
- 替换大脑和认知转移
- 人类如何认识事物

## 数学
- 数学证明的观念会发生改变
    - 数学证明最重要的是检验，任何形式的数学证明将被接受。计算机辅助证明也可以被接受。
    - 数学的根本不在于密密麻麻的数字，而在于证明的过程和模式。

## 复杂性科学
- 复杂性科学在计算机的帮助下将会有更加显著和切实的发展。

## 文化教育
- 我们对于新的观念和认识会变得更加宽容
- 教育将更加注重个人经验。同时，虚拟技术的发展将使得我们更容易的获取人生经历和体验。

## 人文道德
- 一个更新的更现代的基于新的科学研究的道德理论将会产生。以此来规范人们的行为和人类发展的方向。
- 新的科学将有望完善更精确的人性模型。解答包括行为的主观和客观，感觉的真实和虚拟等问题。
- 遗传学和认知科学的发展将使得人们更加幸福。本文作者是心理学家，在文中表示将发展一门新的系统的现象学，观察不同人的意识波动规律，使人更加幸福。
