### ISSUE TITLE
备稿：5月22日 分享

### ISSUE THREAD

**Issue by gsk475** [zsqk/news#58]

**Comment by 504542565** [comment]
## Node.js事件

## 什么是事件轮询
- 事件循环是 Node.js 处理非阻塞 I/O 操作的机制——尽管 JavaScript 是单线程处理的——当有可能的时候，它们会把操作转移到系统内核中去。

## 事件轮询机制解析
- 当 Node.js 启动后，它会初始化事件轮询；处理已提供的输入脚本（或丢入 REPL，本文不涉及到），它可能会调用一些异步的 API、调度定时器，或者调用 process.nextTick()，然后开始处理事件循环。

```
┌───────────────────────────┐
┌─>│           timers          │
│  └─────────────┬─────────────┘
│  ┌─────────────┴─────────────┐
│  │     pending callbacks     │
│  └─────────────┬─────────────┘
│  ┌─────────────┴─────────────┐
│  │       idle, prepare       │
│  └─────────────┬─────────────┘      ┌───────────────┐
│  ┌─────────────┴─────────────┐      │   incoming:   │
│  │           poll            │<─────┤  connections, │
│  └─────────────┬─────────────┘      │   data, etc.  │
│  ┌─────────────┴─────────────┐      └───────────────┘
│  │           check           │
│  └─────────────┬─────────────┘
│  ┌─────────────┴─────────────┐
└──┤      close callbacks      │
   └───────────────────────────┘
```

## 阶段概述
- 1. 定时器：本阶段执行已经被 setTimeout() 和 setInterval() 的调度回调函数。
- 2. 待定回调：执行延迟到下一个循环迭代的 I/O 回调。
- 3. idle, prepare：仅系统内部使用。
- 4. 轮询：检索新的 I/O 事件;执行与 I/O 相关的回调（几乎所有情况下，除了关闭的回调函数，那些由计时器和 setImmediate() 调度的之外），其余情况 node 将在适当的时候在此阻塞。
- 5. 检测：setImmediate() 回调函数在这里执行。
- 6. 关闭的回调函数：一些关闭的回调函数，如：socket.on('close', ...)。

- 在每次运行的事件循环之间，Node.js 检查它是否在等待任何异步 I/O 或计时器，如果没有的话，则完全关闭。
